# Generated by Django 5.2.1 on 2025-05-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='shop/pp/default_profile.jpeg', null=True, upload_to='shop/pp'),
        ),
    ]
