# Generated by Django 5.2.1 on 2025-05-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='templates/shop/pp/default_profile.jpeg', null=True, upload_to='media/profile_pics'),
        ),
    ]
