# Generated by Django 5.2.1 on 2025-05-24 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_category_alter_userprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destinations',
            new_name='Destination',
        ),
    ]
