# Generated by Django 5.2.1 on 2025-05-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='place',
            field=models.CharField(default='', max_length=100),
        ),
    ]
