# Generated by Django 5.2.1 on 2025-05-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_destination_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=5000)),
                ('phone', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=50)),
                ('visit_date', models.DateField(max_length=50)),
                ('best_part', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='para',
            field=models.TextField(null=True),
        ),
    ]
