# Generated by Django 5.2.1 on 2025-05-27 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_hotels_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.category'),
        ),
    ]
