# Generated by Django 5.2.1 on 2025-05-27 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_hotels_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='ratings',
            field=models.CharField(default=5, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('ratings', models.CharField(blank=True, default='5', max_length=100, null=True)),
                ('price', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotels/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.category')),
            ],
        ),
    ]
