# Generated by Django 5.2.1 on 2025-05-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_destination_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.CharField(default='', max_length=50),
        ),
    ]
